### ISSUE TITLE
NavBar on Pixel

### ISSUE THREAD

**Issue by georgestephanis** [LezWatch/lwtv-underscores#4]
I had DM'd @Ipstenu with the following screencap from my Google Pixel (non-XL) yesterday:

![ybsjna3v](https://user-images.githubusercontent.com/941023/31098620-39fcfc64-a791-11e7-8ff8-797a9b259316.jpg)

Looks like she [tried to resolve the issue](https://github.com/LezWatch/lwtv-underscores/commit/f127a97531c80eb768f76f739684cea50c143574) but it still seems to be a bit finnicky on narrow viewports:

<img width="604" alt="screen shot 2017-10-02 at 4 48 59 pm" src="https://user-images.githubusercontent.com/941023/31098730-9e494a10-a791-11e7-878d-93e550f2d142.png">

It happens at varying widths from ~576px on up.

If I comment out this line:

https://github.com/LezWatch/lwtv-underscores/blob/21f112eec5333e12d164362844843bc7bec684d2/style.css#L1678

and replace it with

```css
margin-left: 20px !important;
```

it seems to do better.  (the `!important` is necessary because `.ml-auto` also has one)

**Comment by Ipstenu** [comment]
Thank you, George! I'll get on this :)
